#!/usr/bin/env python3

import curses
import sys

from boatdclient import Boat

boatd_text = '''▄▄                                            ▄▄
██                              ██            ██
██▄███▄    ▄████▄    ▄█████▄  ███████    ▄███▄██
██▀  ▀██  ██▀  ▀██   ▀ ▄▄▄██    ██      ██▀  ▀██
██    ██  ██    ██  ▄██▀▀▀██    ██      ██    ██
███▄▄██▀  ▀██▄▄██▀  ██▄▄▄███    ██▄▄▄   ▀██▄▄███
▀▀ ▀▀▀      ▀▀▀▀     ▀▀▀▀ ▀▀     ▀▀▀▀     ▀▀▀ ▀▀'''.splitlines()

def main(stdscr, doot):
    boat = Boat(auto_update=False)

    curses.halfdelay(1)
    curses.curs_set(0)

    while 1:
        boat.update()

        for i, line in enumerate(boatd_text):
            stdscr.addstr(i + 1, 2, line)

        fields = (
            ('heading', boat.heading),
            ('latitude', boat.position.lat),
            ('longitude', boat.position.long),
            ('relative wind', boat.relative_wind),
            ('absolute wind', boat.wind.direction),
        )

        line_length = max([len(l[0]) for l in fields]) + 2

        for i, (label, value) in enumerate(fields):
            padding = ' ' * (line_length - len(label))
            stdscr.addstr(i + 10, 2, '{}:{}'.format(label, padding))
            stdscr.addstr('{}'.format(value), curses.A_BOLD)

        stdscr.refresh()
        try:
            c = stdscr.getch()
            if c == ord('q'):
                sys.exit()
        except Exception as e:
            print(e)



if __name__ == '__main__':
    curses.wrapper(main, [])
