#!/usr/bin/env python3

import curses
import sys

from boatdclient import Boat


def main(stdscr, doot):
    boat = Boat(auto_update=False)

    curses.halfdelay(1)
    curses.curs_set(0)

    while 1:
        boat.update()

        fields = (
            ('heading', boat.heading),
            ('latitude', boat.position.lat),
            ('longitude', boat.position.long),
        )

        for i, (label, value) in enumerate(fields):
            stdscr.addstr(i + 2, 2, '{}:	'.format(label))
            stdscr.addstr('{}'.format(value), curses.A_BOLD)

        stdscr.refresh()
        try:
            c = stdscr.getch()
            if c == ord('q'):
                sys.exit()
        except Exception as e:
            print(e)



if __name__ == '__main__':
    curses.wrapper(main, [])
